version: '3.4'

services:
  adsfront:
    image: ${DOCKER_REGISTRY-}adsfront
    build:
      context: .
      dockerfile: ADSFront/Dockerfile
    environment:
      DATASTORE_HOST: datastore
      GAMEPLAYWORKER_HOST: adsgameplayworker
    depends_on:
      - adsloginworker
      - adsgameplayworker

  adsloginworker:
    image: ${DOCKER_REGISTRY-}adsloginworker
    build:
      context: .
      dockerfile: ADSLoginWorker/Dockerfile
    environment:
      DATASTORE_HOST: datastore
    depends_on:
      - datastore

  adsgameplayworker:
    image: ${DOCKER_REGISTRY-}adsgameplayworker
    build:
      context: .
      dockerfile: ADSGameplayWorker/Dockerfile
    environment:
      DATASTORE_HOST: datastore
    depends_on:
      - datastore

  datastore:
    image: mongo
    restart: always
    command: --quiet --syslog
    expose:
        - "27017"
    volumes:
        - datastore-data:/data/db
        - mongo-config:/data/configdb

volumes:
  datastore-data:
  mongo-config: